# Pandas Series

**A series is a one dimentional labeled array use for holdiing any type of data. The axis labels are also called the index.**

# Creating Series

In [1]:
import numpy as np
import pandas as pd

In [3]:
my_list = ['A', 'B', 'C']
my_arr = np.array([1,2,3])
my_dict = {1:10, 2:20, 3:30}

In [8]:
print(pd.Series(my_list))
print(pd.Series(my_arr,index=my_list))
print(pd.Series(my_dict))

0    A
1    B
2    C
dtype: object
A    1
B    2
C    3
dtype: int64
1    10
2    20
3    30
dtype: int64

# Pandas DataFrame

**A data Frame is a collection of multiple Series**

# Creating a Data Frame

In [14]:
# creating a data frame using dictionaries 
student_dict = {
    "ID": [101, 102, 103, 104],
    "Name": ["Dhruv", "Rahul", "Priya", "Neha"],
    "Age": [19, 20, 18, 21],
    "Course": ["AI/ML", "Web Dev", "Data Science", "Cyber Security"]
}
df = pd.DataFrame(student_dict)
df

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

In [15]:
# Craeting a data frame using lists
student_list = [
    [101, "Dhruv", 19, "AI/ML"],
    [102, "Rahul", 20, "Web Dev"],
    [103, "Priya", 18, "Data Science"],
    [104, "Neha", 21, "Cyber Security"]
]

df_list = pd.DataFrame(student_list)
df_list

     0      1   2               3
0  101  Dhruv  19           AI/ML
1  102  Rahul  20         Web Dev
2  103  Priya  18    Data Science
3  104   Neha  21  Cyber Security

In [16]:
columns = ["ID", "Name", "Age", "Course"]
df_list2 = pd.DataFrame(student_list, columns= columns)
df_list2

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

**Selection and indexing of Columns**

In [21]:
df_list2["Name"]
df_list2[["Name", "Age"]]

    Name  Age
0  Dhruv   19
1  Rahul   20
2  Priya   18
3   Neha   21

**Creating a new Column**

In [28]:
df_list2["Salary"] = [20000, 10000, 15000, 12000]
df_list2

    ID   Name  Age          Course  Salary
0  101  Dhruv   19           AI/ML   20000
1  102  Rahul   20         Web Dev   10000
2  103  Priya   18    Data Science   15000
3  104   Neha   21  Cyber Security   12000

**Removing Columns**

In [39]:
#df_list2.drop("Salary", axis=1) #Column is remove but not from memory
df_list2 #still exist 
#df_list2.drop("Salary", axis=1, inplace=True) #remove column from memory
df_list2

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

**Selecting Rows**

In [40]:
df_list2

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

In [42]:
df_list2.loc[0] # single row
df_list2.loc[[0,1]] # multiple row

    ID   Name  Age   Course
0  101  Dhruv   19    AI/ML
1  102  Rahul   20  Web Dev

**Selecting Subsets of Rows and Columns**

In [44]:
df_list2

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

In [46]:
df_list2.loc[[0,1,2]][["Name", "Age"]]

    Name  Age
0  Dhruv   19
1  Rahul   20
2  Priya   18

**Conditional Selection**

In [47]:
df_list2

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

In [ ]:
# Select the Employees whose age is < 20 and course = "AIML"
df_list2[(df_list2["Age"] < 20) & (df_list2["Course"] == "AI/ML")]

In [65]:
# Select the Employee whose age is >= 20 and course == "Web Dev"
df_list2[(df_list2["Age"] >= 20) & (df_list2["Course"] == "Web Dev")]

    ID   Name  Age   Course
1  102  Rahul   20  Web Dev

# Missing Data

**Finding Missing Data**

In [74]:
data = {
    "A": [np.nan, 20, 30, 40],
    "B": [10, np.nan, 30, 40],
    "C": [10, 20, 30, 40],
    "D": [10, np.nan, 30, np.nan]
}
df = pd.DataFrame(data)
df

      A     B   C     D
0   NaN  10.0  10  10.0
1  20.0   NaN  20   NaN
2  30.0  30.0  30  30.0
3  40.0  40.0  40   NaN

In [75]:
df.isna()

       A      B      C      D
0   True  False  False  False
1  False   True  False   True
2  False  False  False  False
3  False  False  False   True

In [76]:
df.isna().sum()

A    1
B    1
C    0
D    2
dtype: int64

In [79]:
df.isna().any()

A     True
B     True
C    False
D     True
dtype: bool

**Removing Missing Data**

In [80]:
df.dropna() # remove all rows whose have NaN value

      A     B   C     D
2  30.0  30.0  30  30.0

In [84]:
df.dropna(thresh=3) # thresh means number of non zero element present in row

      A     B   C     D
0   NaN  10.0  10  10.0
2  30.0  30.0  30  30.0
3  40.0  40.0  40   NaN

**Filling Mising Data**

In [86]:
df

      A     B   C     D
0   NaN  10.0  10  10.0
1  20.0   NaN  20   NaN
2  30.0  30.0  30  30.0
3  40.0  40.0  40   NaN

df.fillna(0)

In [89]:
values = {'A': 10, 'B' : 20, 'C' : 30, 'D': 40}
df.fillna(value=values)

      A     B   C     D
0  10.0  10.0  10  10.0
1  20.0  20.0  20  40.0
2  30.0  30.0  30  30.0
3  40.0  40.0  40  40.0

In [90]:
df.fillna(df.mean())

      A          B   C     D
0  30.0  10.000000  10  10.0
1  20.0  26.666667  20  20.0
2  30.0  30.000000  30  30.0
3  40.0  40.000000  40  20.0

# Merging Joining and Concatenation

**Merging**

In [125]:
# Data Frame for Employees
employees = {
    "Emp_ID": [101, 102, 103, 104],
    "Name": ["Dhruv", "Rahul", "Priya", "Neha"],
    "Department_ID": [1, 2, 1, 3]
}
df_employees = pd.DataFrame(employees)
# Data Frame for Departments
departments = {
    "Department_ID": [1, 2, 3],
    "Department_Name": ["AI/ML", "Web Dev", "Cyber Security"]
}
df_departments = pd.DataFrame(departments)

In [126]:
df_employees
df_departments

   Department_ID Department_Name
0              1           AI/ML
1              2         Web Dev
2              3  Cyber Security

In [127]:
pd.merge(df_employees, df_departments, on= 'Department_ID')

   Emp_ID   Name  Department_ID Department_Name
0     101  Dhruv              1           AI/ML
1     102  Rahul              2         Web Dev
2     103  Priya              1           AI/ML
3     104   Neha              3  Cyber Security

In [128]:
pd.merge(df_employees, df_departments, on= 'Department_ID', how = 'inner')

   Emp_ID   Name  Department_ID Department_Name
0     101  Dhruv              1           AI/ML
1     102  Rahul              2         Web Dev
2     103  Priya              1           AI/ML
3     104   Neha              3  Cyber Security

In [129]:
pd.merge(df_employees, df_departments, on= 'Department_ID', how = 'outer')

   Emp_ID   Name  Department_ID Department_Name
0     101  Dhruv              1           AI/ML
1     103  Priya              1           AI/ML
2     102  Rahul              2         Web Dev
3     104   Neha              3  Cyber Security

In [130]:
pd.merge(df_employees, df_departments, on= 'Department_ID', how = 'left') # left means according to df_employees

   Emp_ID   Name  Department_ID Department_Name
0     101  Dhruv              1           AI/ML
1     102  Rahul              2         Web Dev
2     103  Priya              1           AI/ML
3     104   Neha              3  Cyber Security

In [131]:
pd.merge(df_employees, df_departments, on= 'Department_ID', how = 'right') # right means according to df_departments

   Emp_ID   Name  Department_ID Department_Name
0     101  Dhruv              1           AI/ML
1     103  Priya              1           AI/ML
2     102  Rahul              2         Web Dev
3     104   Neha              3  Cyber Security

**Concatenation**

In [140]:
pd.concat([df_employees,df_departments])

   Emp_ID   Name  Department_ID Department_Name
0   101.0  Dhruv              1             NaN
1   102.0  Rahul              2             NaN
2   103.0  Priya              1             NaN
3   104.0   Neha              3             NaN
0     NaN    NaN              1           AI/ML
1     NaN    NaN              2         Web Dev
2     NaN    NaN              3  Cyber Security

**Joining**

In [151]:
df1 = {"Name" : ["Bob", "Alex", "Micheal"]}
df_df1 = pd.DataFrame(df1)
df2 = {"Marks" : [80, 90, 70]}
df_df2 = pd.DataFrame(df2,index=[2,3,4])

In [152]:
df_df1.join(df_df2)

      Name  Marks
0      Bob    NaN
1     Alex    NaN
2  Micheal   80.0

In [153]:
df_df2.join(df_df1)

   Marks     Name
2     80  Micheal
3     90      NaN
4     70      NaN