# Pandas Series

**A series is a one dimentional labeled array use for holdiing any type of data. The axis labels are also called the index.**

# Creating Series

In [1]:
import numpy as np
import pandas as pd

In [3]:
my_list = ['A', 'B', 'C']
my_arr = np.array([1,2,3])
my_dict = {1:10, 2:20, 3:30}

In [8]:
print(pd.Series(my_list))
print(pd.Series(my_arr,index=my_list))
print(pd.Series(my_dict))

0    A
1    B
2    C
dtype: object
A    1
B    2
C    3
dtype: int64
1    10
2    20
3    30
dtype: int64

# Pandas DataFrame

**A data Frame is a collection of multiple Series**

# Creating a Data Frame

In [14]:
# creating a data frame using dictionaries 
student_dict = {
    "ID": [101, 102, 103, 104],
    "Name": ["Dhruv", "Rahul", "Priya", "Neha"],
    "Age": [19, 20, 18, 21],
    "Course": ["AI/ML", "Web Dev", "Data Science", "Cyber Security"]
}
df = pd.DataFrame(student_dict)
df

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

In [15]:
# Craeting a data frame using lists
student_list = [
    [101, "Dhruv", 19, "AI/ML"],
    [102, "Rahul", 20, "Web Dev"],
    [103, "Priya", 18, "Data Science"],
    [104, "Neha", 21, "Cyber Security"]
]

df_list = pd.DataFrame(student_list)
df_list

     0      1   2               3
0  101  Dhruv  19           AI/ML
1  102  Rahul  20         Web Dev
2  103  Priya  18    Data Science
3  104   Neha  21  Cyber Security

In [16]:
columns = ["ID", "Name", "Age", "Course"]
df_list2 = pd.DataFrame(student_list, columns= columns)
df_list2

    ID   Name  Age          Course
0  101  Dhruv   19           AI/ML
1  102  Rahul   20         Web Dev
2  103  Priya   18    Data Science
3  104   Neha   21  Cyber Security

**Selection and indexing of Columns**

In [21]:
df_list2["Name"]
df_list2[["Name", "Age"]]

    Name  Age
0  Dhruv   19
1  Rahul   20
2  Priya   18
3   Neha   21

**Creating a new Column**

In [28]:
df_list2["Salary"] = [20000, 10000, 15000, 12000]
df_list2

    ID   Name  Age          Course  Salary
0  101  Dhruv   19           AI/ML   20000
1  102  Rahul   20         Web Dev   10000
2  103  Priya   18    Data Science   15000
3  104   Neha   21  Cyber Security   12000

**Removing Columns**

In [35]:
df_list2.drop("Salary", axis=1) #Column is remove but not from memory
df_list2 #still exist
df_list2.drop("Salary", axis=1, inplace=True)
df_list2

KeyError: "['Salary'] not found in axis"

**Selecting Rows**

**Selecting Subsets of Rows and Columns**

**Conditional Selection**